name: Rational Test Automation Server

on: workflow_dispatch

jobs:
    OTS-Action:
        runs-on: self-hosted
        name: Rational Test Automation Server
        steps:
         - name: Execute Test
           uses: IBM/devopsauto-testserver-actions@main
           with:
            serverUrl: <https://myserver>
            offlineToken: <xxxxx>
            teamspace: <MyTeam>
            project: <MyProject>
            branch: <main>
            assetId: <yyyyyyy>
